name: ci
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm i -g htmlhint

      - name: Run html linter
        run: npx htmlhint index.html
  ai-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - shell: bash
        env:
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
        run: |
          pwd \
          export DIFF=$(git diff origin/main) \
          curl -X POST "https://arnost-havelka-1536-resource.openai.azure.com/openai/v1/chat/completions" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AZURE_API_KEY" \
          -d '{
              "messages" : [
                  {
                          "role": "user",
                          "content": "these are my code changes: $DIFF"
                  },
                  {
                          "role": "assistant",
                          "content": "professional programmer with knowledge of clean code principles"
                  },
                  {
                          "role": "user",
                          "content": "refactor this code and fix bugs"
                  }
          ],
               "max_completion_tokens" : 13107,
               "temperature" : 1,
               "top_p" : 1,
               "stop" : [],
               "frequency_penalty" : 0,
               "presence_penalty" : 0,
              "model": "gpt-4.1"
          }'
    
